// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOrgGJJKR75SoAWwQW2mnqSy_2iiziVrY',
    appId: '1:42781952660:web:41ead756e5f6329a0f4281',
    messagingSenderId: '42781952660',
    projectId: 'staz-final',
    authDomain: 'staz-final.firebaseapp.com',
    storageBucket: 'staz-final.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8LsfW7jq58pubwO1vsDzX8FEssz7jE4c',
    appId: '1:42781952660:android:16099f86f36f14b90f4281',
    messagingSenderId: '42781952660',
    projectId: 'staz-final',
    storageBucket: 'staz-final.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAB-vn1bXILxAEkMAG2F8LVkYlb-avDdsw',
    appId: '1:42781952660:ios:6ac99cd9135e1a2b0f4281',
    messagingSenderId: '42781952660',
    projectId: 'staz-final',
    storageBucket: 'staz-final.appspot.com',
    iosClientId: '42781952660-ijv6bkhth0khes41j17gkoaqlt8hj8t4.apps.googleusercontent.com',
    iosBundleId: 'com.example.appdevfinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAB-vn1bXILxAEkMAG2F8LVkYlb-avDdsw',
    appId: '1:42781952660:ios:6ac99cd9135e1a2b0f4281',
    messagingSenderId: '42781952660',
    projectId: 'staz-final',
    storageBucket: 'staz-final.appspot.com',
    iosClientId: '42781952660-ijv6bkhth0khes41j17gkoaqlt8hj8t4.apps.googleusercontent.com',
    iosBundleId: 'com.example.appdevfinal',
  );
}
